#' Add multiple realizations to GRF object
#'
#' Generates multiple realizations from the GRF object specified as a parameter, and adds them to the object.
#' See \code{\link{add.grf.realization}} for details.
#'
#' @param grf.object A GRF object generated by \code{\link{generate.grf.object}}.
#' @param num.realizations The number of realizations to be added.
#' @param realization.names A character vector specifying the names used for each realization.
#' @param seed Optional. Must be a numeric vector of length \code{num.realizations}.
#'
#' @details Either \code{num.realizations} or \code{realization.names} must be specified.
#'
#' @return The GRF object with the realizations added to the \code{realizations} list.
#'
#' @examples
#' # Prepare GRF object
#' grf.object = generate.grf.object(0, 1, 0, 1, 100, 100)
#' # Add two realizations to object
#' grf.object = add.multiple.grf.realizations(grf.object, realization.names = c("u", "v"))
#' # Extract data frames
#' realization.1.df = get.realization.df(grf.object, realization.name = "u")
#' realization.2.df = get.realization.df(grf.object, realization.number = 2)
#' # Create combined data frame for plotting
#' combined.df = rbind(realization.1.df, realization.2.df)
#' combined.df$facet.var = rep(1:2, each = nrow(realization.1.df))
#' # Plot realizations side by side
#' library(ggplot2)
#' ggplot()+
#'   geom_raster(data = combined.df, aes(x = x, y = y, fill = z))+
#'   coord_fixed()+
#'   facet_grid(cols = vars(facet.var))
#'
#' @export
#' @author Mathias Isaksen

add.multiple.grf.realizations = function(grf.object, num.realizations = NULL, realization.names = NULL, seed = NULL) {
  if (is.null(num.realizations) & !is.null(realization.names)) {
    num.realizations = length(realization.names)
  } else {
    stop("Both num.realizations and realization.names is missing.")
  }

  for (i in 1:num.realizations) {
    grf.object = add.grf.realization(grf.object, realization.name = realization.names[i], seed = seed[i])
  }
  return(grf.object)
}
