#' Add realization to GRF object
#'
#' Generates a realization from the GRF object specified as a parameter, and adds it to the object.
#'
#' @details The object \code{chol.object}, which is needed for computing the realization, is computed and added to \code{grf.object}
#' the first time that \code{add.grf.realization} is run.
#'
#' @param grf.object A GRF object generated by \code{\link{generate.grf.object}}.
#' @param seed Optional, the seed used for generating the realization.
#'
#' @return The GRF object with the realization added to the \code{realizations} list.
#'
#' @examples
#' # Prepare GRF object
#' grf.object = generate.grf.object(0, 1, 0, 1, 100, 100)
#' # Add two realizations to object
#' grf.object = add.grf.realization(grf.object, seed = 0)
#' grf.object = add.grf.realization(grf.object, seed = 1)
#' # Extract data frames
#' realization.1.df = get.realization.df(grf.object, realization.number = 1)
#' realization.2.df = get.realization.df(grf.object, realization.number = 2)
#' # Create combined data frame for plotting
#' combined.df = rbind(realization.1.df, realization.2.df)
#' combined.df$facet.var = rep(1:2, each = nrow(realization.1.df))
#' # Plot realizations side by side
#' library(ggplot2)
#' ggplot()+
#'   geom_raster(data = combined.df, aes(x = x, y = y, fill = z))+
#'   coord_fixed()+
#'   facet_grid(cols = vars(facet.var))
#'
#' @export
#' @author Mathias Isaksen
add.grf.realization = function(grf.object, realization.name = NULL, seed = NULL) {
  if (is.null(grf.object$model.components$chol.object)) {
    grf.object$model.components$chol.object = permuted.cholesky.decomp(grf.object$model.components$Q)
  }

  realization.name = ifelse(is.null(realization.name), as.character(length(grf.object$realizations)+1), realization.name)
  if (!is.character(realization.name)) {
    realization.name = as.character(realization.name)
  }

  if (is.null(grf.object$realizations)) {
    seed = ifelse(is.null(seed), grf.object$initial.seed, seed)
  }

  new.realization = generate.gmrf.realization(chol.object = grf.object$model.components$chol.object, seed = seed)
  grf.object$realizations[[realization.name]] = new.realization
  return(grf.object)
}
