#' Normalize GRF realizations
#'
#' This function ensures that each realization is between 0 and 1 in value, and that the realizations sum to 1 at every location.
#'
#' @param grf.object A GRF object generated by \code{\link{generate.grf.object}}.
#' @param use.ecdf Specifices whether the realizations should be rescaled between 0 and 1 by a min-max scaling (\code{use.ecdf = FALSE}), or if a ECDF scaling should be used (\code{use.ecdf = TRUE}).
#'
#' @return A normalized GRF object.
#'
#' @export
#' @author Mathias Isaksen

normalize.grf.realizations = function(grf.object, use.ecdf = TRUE) {
  num.realizations = length(grf.object$realizations)
  realization.matrix = matrix(NA, nrow = nrow(grf.object$grid), ncol = num.realizations)
  for (i in 1:num.realizations) {
    if (use.ecdf) {
      real.ecdf = ecdf(grf.object$realizations[[i]])
      grf.object$realizations[[i]] = real.ecdf(grf.object$realizations[[i]])
    } else {
      grf.object$realizations[[i]] = standardize(grf.object$realizations[[i]])
    }
    realization.matrix[, i] = grf.object$realizations[[i]]
  }
  realization.matrix = t(apply(realization.matrix, 1, function(x) x/sum(x)))
  for (i in 1:num.realizations) {
    grf.object$realizations[[i]] = realization.matrix[, i]
  }
  return(grf.object)
}
