#' Normalize GRF realizations
#'
#' This function ensures that each realization is between 0 and 1 in value, and that the realizations sum to 1 at every location.
#'
#' @param grf.object A GRF object generated by \code{\link{generate.grf.object}}.
#'
#'
#' @return A normalized GRF object.
#'
#' @export
#' @author Mathias Isaksen

normalize.grf.realizations = function(grf.object) {
  num.realizations = length(grf.object$realizations)
  realization.matrix = matrix(NA, nrow = nrow(grf.object$grid), ncol = num.realizations)
  grf.object$realizations = lapply(grf.object$realizations, function(x) standardize(x))
  for (i in 1:num.realizations) {
    realization.matrix[, i] = grf.object$realizations[[i]]
  }
  realization.matrix = t(apply(realization.matrix, 1, function(x) x/sum(x)))
  for (i in 1:num.realizations) {
    grf.object$realizations[[i]] = realization.matrix[, i]
  }
  return(grf.object)
}
